BEGIN;
DO $$
BEGIN


UPDATE language SET date_format = 'YYYY-MM-DD', time_format = 'h:mm' WHERE language_code = 'pt-PT';
UPDATE language SET date_format = 'YYYY-MM-DD', time_format = 'h:mm' WHERE language_code = 'de-DE';
UPDATE language SET date_format = 'YYYY-MM-DD', time_format = 'h:mm' WHERE language_code = 'en-US';
UPDATE language SET date_format = 'YYYY-MM-DD', time_format = 'h:mm' WHERE language_code = 'nl-NL';
UPDATE language SET date_format = 'YYYY-MM-DD', time_format = 'h:mm' WHERE language_code = 'fr-FR';
UPDATE language SET date_format = 'YYYY-MM-DD', time_format = 'h:mm' WHERE language_code = 'it-IT';
UPDATE language SET date_format = 'YYYY-MM-DD', time_format = 'h:mm' WHERE language_code = 'ja-JP';
UPDATE language SET date_format = 'YYYY-MM-DD', time_format = 'h:mm' WHERE language_code = 'es-ES';
UPDATE language SET currency_format = 'WS$1,234,567.57' WHERE language_code = 'en_ZA';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'he_IL';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'it_IT_EURO';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'mn_MN';
UPDATE language SET currency_format = '1234567.57' WHERE language_code = 'my_mm';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'nb_NO';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'nl_NL_EURO';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'pt_PT_EURO';
UPDATE language SET currency_format = '€1.234,56' WHERE language_code = 'pt-PT';
UPDATE language SET currency_format = 'CHF1’234’567.57' WHERE language_code = 'de-DE';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'en-US';
    UPDATE language SET currency_format = '€1.234.567,57' WHERE language_code = 'nl-NL';
    UPDATE language SET currency_format = '1234567.57CHF' WHERE language_code = 'fr-FR';
    UPDATE language SET currency_format = 'CHF1’234’567.57' WHERE language_code = 'it-IT';
    UPDATE language SET currency_format = '¥1,234' WHERE language_code = 'ja-JP';
    UPDATE language SET currency_format = '$1.234.567,57' WHERE language_code = 'es-ES';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'N/A';
    UPDATE language SET currency_format = 'R1,234,567.57' WHERE language_code = 'af_ZA';
    UPDATE language SET currency_format = 'R1234567,57' WHERE language_code = 'am_ET';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_AE';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_BH';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_DZ';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_EG';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_IQ';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_JO';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_KW';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_LB';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_LY';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_MA';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_OM';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_QA';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_SA';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_SD';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_SY';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_TN';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ar_YE';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'az_AZ';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'be_BY';
    UPDATE language SET currency_format = '1234567,57Br' WHERE language_code = 'bg_BG';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'bn_BD';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'bn_IN';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'bs_BA';
    UPDATE language SET currency_format = '1.234.567,57KM' WHERE language_code = 'ca_ES';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'ca_ES_EURO';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'cs_CZ';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'cy_GB';
    UPDATE language SET currency_format = '£1,234,567.57' WHERE language_code = 'da_DK';
    UPDATE language SET currency_format = '1.234.567,57kr.' WHERE language_code = 'de_AT';
    UPDATE language SET currency_format = '€1.234.567,57' WHERE language_code = 'de_AT_EURO';
    UPDATE language SET currency_format = '€1.234.567,57' WHERE language_code = 'de_BE';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'de_CH';
    UPDATE language SET currency_format = 'CHF1’234’567.57' WHERE language_code = 'de_DE';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'de_DE_EURO';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'de_LU';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'de_LU_EURO';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'dz_BT';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'el_GR';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'en_AG';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_AU';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_BB';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_BM';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_BS';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_BW';
    UPDATE language SET currency_format = 'P1,234,567.57' WHERE language_code = 'en_BZ';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_CA';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_CM';
    UPDATE language SET currency_format = 'FCFA1,234,567.57' WHERE language_code = 'en_ER';
    UPDATE language SET currency_format = 'Nfk1,234,567.57' WHERE language_code = 'en_FJ';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_FK';
    UPDATE language SET currency_format = '£1,234,567.57' WHERE language_code = 'en_GB';
    UPDATE language SET currency_format = '£1,234,567.57' WHERE language_code = 'en_GH';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'en_GI';
    UPDATE language SET currency_format = '£1,234,567.57' WHERE language_code = 'en_GM';
    UPDATE language SET currency_format = 'D1,234,567.57' WHERE language_code = 'en_GY';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_HK';
    UPDATE language SET currency_format = 'HK$1,234,567.57' WHERE language_code = 'en_ID';
    UPDATE language SET currency_format = 'IDR1,234,567.57' WHERE language_code = 'en_IE';
    UPDATE language SET currency_format = '€ 1,234,567.57' WHERE language_code = 'en_IE_EURO';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'en_IN';
    UPDATE language SET currency_format = '$1234567.57' WHERE language_code = 'en_JM';
    UPDATE language SET currency_format = '$1234567.57' WHERE language_code = 'en_KE';
    UPDATE language SET currency_format = 'Ksh1,234,567.57' WHERE language_code = 'en_KY';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_LR';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_MG';
    UPDATE language SET currency_format = 'Ar1,234,567.57' WHERE language_code = 'en_MU';
    UPDATE language SET currency_format = 'Rs1,234,567.57' WHERE language_code = 'en_MW';
    UPDATE language SET currency_format = 'MK1,234,567.57' WHERE language_code = 'en_MY';
    UPDATE language SET currency_format = 'RM1,234,567.57' WHERE language_code = 'en_NA';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_NG';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'en_NZ';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_PG';
    UPDATE language SET currency_format = 'K1,234,567.57' WHERE language_code = 'en_PH';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'en_PK';
    UPDATE language SET currency_format = 'Rs1,234,567.57' WHERE language_code = 'en_RW';
    UPDATE language SET currency_format = 'RF1,234,567.57' WHERE language_code = 'en_SB';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_SC';
    UPDATE language SET currency_format = 'SR1,234,567.57' WHERE language_code = 'en_SG';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_SH';
    UPDATE language SET currency_format = '£1,234,567.57' WHERE language_code = 'en_SL';
    UPDATE language SET currency_format = 'Le1,234,567.57' WHERE language_code = 'en_SX';
    UPDATE language SET currency_format = 'NAf.1,234,567.57' WHERE language_code = 'en_SZ';
    UPDATE language SET currency_format = 'E1,234,567.57' WHERE language_code = 'en_TO';
    UPDATE language SET currency_format = 'T$1,234,567.57' WHERE language_code = 'en_TT';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_TZ';
    UPDATE language SET currency_format = 'TSh1,234,567.57' WHERE language_code = 'en_UG';
    UPDATE language SET currency_format = 'USh1,234,567.57' WHERE language_code = 'en_US';
    UPDATE language SET currency_format = 'VT1,234,567.57' WHERE language_code = 'en_VU';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'en_WS';
    UPDATE language SET currency_format = 'R1234567,57' WHERE language_code = 'es_AR';
    UPDATE language SET currency_format = '$1.234.567,57' WHERE language_code = 'es_BO';
    UPDATE language SET currency_format = 'Bs1.234.567,57' WHERE language_code = 'es_CL';
    UPDATE language SET currency_format = '$1.234.567,57' WHERE language_code = 'es_CO';
    UPDATE language SET currency_format = '$1.234.567,57' WHERE language_code = 'es_CR';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'es_CU';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'es_DO';
    UPDATE language SET currency_format = 'RD$1,234,567.57' WHERE language_code = 'es_EC';
    UPDATE language SET currency_format = '$1.234.567,57' WHERE language_code = 'es_ES';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'es_ES_EURO';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'es_GT';
    UPDATE language SET currency_format = 'Q1,234,567.57' WHERE language_code = 'es_HN';
    UPDATE language SET currency_format = 'L1,234,567.57' WHERE language_code = 'es_MX';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'es_NI';
    UPDATE language SET currency_format = 'C$1,234,567.57' WHERE language_code = 'es_PA';
    UPDATE language SET currency_format = 'B/.1,234,567.57' WHERE language_code = 'es_PE';
    UPDATE language SET currency_format = 'S/1,234,567.57' WHERE language_code = 'es_PR';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'es_PY';
    UPDATE language SET currency_format = 'Gs.1.234.567,57' WHERE language_code = 'es_SV';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'es_US';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'es_UY';
    UPDATE language SET currency_format = '$1,234,567.57' WHERE language_code = 'es_VE';
    UPDATE language SET currency_format = '$1.234.567,57' WHERE language_code = 'et_EE';
    UPDATE language SET currency_format = 'Bs.S1.234.567,57' WHERE language_code = 'eu_ES';
    UPDATE language SET currency_format = '1234567,57€' WHERE language_code = 'fa_IR';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'fi_FI';
    UPDATE language SET currency_format = '1234567,57€' WHERE language_code = 'fi_FI_EURO';
    UPDATE language SET currency_format = '1 234 567,57€' WHERE language_code = 'fr_BE';
    UPDATE language SET currency_format = '1 234 567,57€' WHERE language_code = 'fr_CA';
    UPDATE language SET currency_format = '1 234 567.57CHF' WHERE language_code = 'fr_CH';
    UPDATE language SET currency_format = '1 234 567,57€' WHERE language_code = 'fr_FR';
    UPDATE language SET currency_format = '1 234 567,57€' WHERE language_code = 'fr_FR_EURO';
    UPDATE language SET currency_format = '1 234 567,57FG' WHERE language_code = 'fr_GN';
    UPDATE language SET currency_format = '1 234 567,57G' WHERE language_code = 'fr_HT';
    UPDATE language SET currency_format = '1 234 567,57€' WHERE language_code = 'fr_LU';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'fr_LU_EURO';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'fr_ML';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'fr_SN';
    UPDATE language SET currency_format = '1234567,57FCFP' WHERE language_code = 'ga_IE';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ga_IE_EURO';
    UPDATE language SET currency_format = '€ 1,234,567.57' WHERE language_code = 'gu_IN';
    UPDATE language SET currency_format = '1.234.567,57€' WHERE language_code = 'iw_IL';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'hi_IN';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'hr_HR';
    UPDATE language SET currency_format = '1.234.567,57HRK' WHERE language_code = 'hu_HU';
    UPDATE language SET currency_format = '1234567,57Ft' WHERE language_code = 'hy_AM';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'id_ID';
    UPDATE language SET currency_format = 'Rp1.234.567,57' WHERE language_code = 'is_IS';
    UPDATE language SET currency_format = '1.234.567,57ISK' WHERE language_code = 'it_CH';
    UPDATE language SET currency_format = 'CHF1’234’567.57' WHERE language_code = 'it_IT';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ja_JP';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ka_GE';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'kk_KZ';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'km_KH';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'kn_IN';
    UPDATE language SET currency_format = 'KPW 1,234,567.57' WHERE language_code = 'kp_KP';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ko_KR';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ky_KG';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'lo_LA';
    UPDATE language SET currency_format = '1 234 567,57 €' WHERE language_code = 'lt_LT';
    UPDATE language SET currency_format = '1.234.567,57 €' WHERE language_code = 'lv_LV';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'mk_MK';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ml_IN';
    UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'mr_IN';
UPDATE language SET currency_format = '$1.234.567,57' WHERE language_code = 'ms_BN';
UPDATE language SET currency_format = 'RM 1,234,567.57' WHERE language_code = 'ms_MY';
UPDATE language SET currency_format = '€1,234,567.57' WHERE language_code = 'mt_MT';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'my_MM';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ne_NP';
UPDATE language SET currency_format = 'Afl. 1.234.567,57' WHERE language_code = 'nl_BE';
UPDATE language SET currency_format = '€ 1.234.567,57' WHERE language_code = 'nl_NL';
UPDATE language SET currency_format = 'kr 1 234 567,57' WHERE language_code = 'no_NO';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'or_IN';
UPDATE language SET currency_format = 'Rs. 12,34,567.57' WHERE language_code = 'pa_IN';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'pl_PL';
UPDATE language SET currency_format = 'R$ 1.234.567,57' WHERE language_code = 'pt_BR';
UPDATE language SET currency_format = '1 234 567$57' WHERE language_code = 'pt_PT';
UPDATE language SET currency_format = '1 234 567,57 MTn' WHERE language_code = 'ro_MD';
UPDATE language SET currency_format = '1 234 567,57 €' WHERE language_code = 'ro_RO';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ru_RU';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ru_UA';
UPDATE language SET currency_format = 'Br 1,234,567.57' WHERE language_code = 'si_LK';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'sk_SK';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'sl_SI';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'sq_AL';
UPDATE language SET currency_format = '1.234.567,57 CSD' WHERE language_code = 'sr_RS';
UPDATE language SET currency_format = 'kr 1 234 567,57' WHERE language_code = 'sv_SE';
UPDATE language SET currency_format = 'Ksh 1,234,567.57' WHERE language_code = 'sw_KE';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'ta_IN';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'te_IN';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'th_TH';
UPDATE language SET currency_format = 'R 1 234 567.57' WHERE language_code = 'tl_PH';
UPDATE language SET currency_format = 'CFA 1,234,567.57' WHERE language_code = 'tr_TR';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'uk_UA';
UPDATE language SET currency_format = 'HK$1,234,567.57' WHERE language_code = 'ur_PK';
UPDATE language SET currency_format = 'MOP$1,234,567.57' WHERE language_code = 'uz_UZ';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'vi_VN';
UPDATE language SET currency_format = 'CFA1,234,567.57' WHERE language_code = 'zh_CN';
UPDATE language SET currency_format = '$1,234.56' WHERE language_code = 'zh_HK';
UPDATE language SET currency_format = 'MOP$1,234,567.57' WHERE language_code = 'zh_SG';
UPDATE language SET currency_format = '$1234567.57' WHERE language_code = 'zh_TW';
UPDATE language SET currency_format = '$1234567.57' WHERE language_code = 'zu_ZA';


     RAISE NOTICE 'Data inserted successfully.';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE EXCEPTION 'An error occurred during the insertion. Transaction has been rolled back: %', SQLERRM;
END $$;
COMMIT;